In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [6]:
df.shape

(569, 33)

In [9]:
df.drop(columns =['id', 'Unnamed: 32'], inplace = True)

In [10]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

Train test split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:,0], test_size = 0.2)

Scaling

In [12]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
X_train

array([[ 0.92464763, -0.49496076,  0.88709387, ...,  1.10047988,
         0.39552755, -0.16768496],
       [-0.42134787,  0.38980736, -0.40037687, ..., -0.05295248,
        -1.07440368,  0.04309646],
       [-0.57410539, -0.34108804, -0.57064853, ..., -0.78673178,
         0.25208031, -0.75086571],
       ...,
       [-1.16495995, -0.386769  , -1.14072472, ..., -0.75099378,
         0.00225647, -0.42141379],
       [ 0.62201481,  0.08927471,  0.75354748, ...,  0.97470667,
         0.68564555,  0.41040992],
       [ 1.54144215, -0.07661931,  1.51726594, ...,  1.41184526,
         0.60183369,  0.33864252]])

In [14]:
y_train

253    M
111    B
394    B
118    M
352    M
      ..
489    M
148    B
338    B
479    M
487    M
Name: diagnosis, Length: 455, dtype: object

Label Encoder

In [15]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [16]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1])

Numpy Arrays to Pytorch Tensors

In [17]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [18]:
X_train_tensor.shape

torch.Size([455, 30])

In [20]:
y_train_tensor.shape

torch.Size([455])

Defining the model

In [33]:
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1],1, dtype = torch.float64, requires_grad = True)
    self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)
  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred
  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1- epsilon)

    #calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

Important Parameters

In [39]:
learning_rate = 0.1
epochs = 10

Training Pipeline

In [40]:
model = MySimpleNN(X_train_tensor)
#define loop
for epoch in range(epochs):
  y_pred = model.forward(X_train_tensor)
  print(y_pred)
# loss calculation
loss = model.loss_function(y_pred, y_train_tensor)
print(loss)
#backward pass
loss.backward()
#parameters update
with torch.no_grad():
  model.weights -= learning_rate * model.weights.grad
  model.bias -= learning_rate * model.bias.grad
# zero gradients
model.weights.grad.zero_()
model.bias.grad.zero_()

#print loss in each epoch
print(f'epoch: {epoch}, loss: {loss}')

tensor([[5.0941e-01],
        [9.7292e-01],
        [8.0651e-02],
        [9.9999e-01],
        [1.0000e+00],
        [8.1970e-04],
        [3.8502e-01],
        [8.8785e-01],
        [4.9510e-01],
        [3.6432e-06],
        [3.3922e-06],
        [1.0000e+00],
        [3.7921e-01],
        [3.3530e-04],
        [9.9959e-01],
        [1.1886e-03],
        [9.8905e-01],
        [8.8500e-05],
        [9.9993e-01],
        [1.3977e-03],
        [1.6020e-01],
        [4.3304e-02],
        [2.2282e-01],
        [5.6818e-02],
        [5.1404e-03],
        [9.9845e-01],
        [1.6219e-01],
        [9.4683e-01],
        [1.4133e-02],
        [9.9922e-01],
        [9.9999e-01],
        [9.9572e-01],
        [9.9998e-01],
        [9.9830e-01],
        [8.7178e-01],
        [9.9590e-01],
        [4.0403e-02],
        [8.5369e-04],
        [9.8433e-01],
        [2.6345e-04],
        [1.0000e+00],
        [9.9998e-01],
        [7.6033e-01],
        [8.1483e-01],
        [9.9952e-01],
        [6.5717e-07],
        [2.1040e-02],
        [1.8501e-01],
        [9.9894e-01],
        [4.6295e-05],
        [9.8361e-01],
        [2.7733e-01],
        [3.4401e-03],
        [2.4289e-04],
        [2.9282e-02],
        [9.9962e-01],
        [7.5155e-01],
        [9.9580e-01],
        [2.9348e-01],
        [7.0850e-03],
        [7.4644e-01],
        [1.1903e-02],
        [4.9723e-03],
        [7.4353e-02],
        [9.9850e-01],
        [1.4589e-04],
        [5.3529e-01],
        [7.8295e-02],
        [9.9991e-01],
        [8.0669e-01],
        [1.0000e+00],
        [7.6067e-04],
        [9.9996e-01],
        [5.9253e-04],
        [9.9681e-01],
        [2.5843e-01],
        [5.5852e-03],
        [9.7844e-01],
        [7.3009e-01],
        [3.3929e-02],
        [1.0000e+00],
        [2.2506e-03],
        [5.3282e-06],
        [9.9319e-01],
        [9.9976e-01],
        [3.3504e-04],
        [9.8243e-01],
        [1.5871e-02],
        [3.9569e-02],
        [7.1727e-02],
        [1.0000e+00],
        [9.9999e-01],
        [1.0018e-06],
        [1.0000e+00],
        [1.0000e+00],
        [9.0512e-01],
        [9.9984e-01],
        [2.8304e-04],
        [2.3831e-02],
        [2.0036e-02],
        [9.9995e-01],
        [9.9937e-01],
        [6.7075e-04],
        [9.9097e-01],
        [1.8522e-02],
        [7.2944e-03],
        [1.1664e-05],
        [6.5706e-01],
        [1.0702e-03],
        [2.3147e-02],
        [7.3181e-02],
        [9.9370e-01],
        [1.7428e-01],
        [5.6151e-03],
        [1.5771e-01],
        [4.8090e-02],
        [1.3968e-01],
        [2.2102e-03],
        [4.2453e-01],
        [9.9998e-01],
        [5.9279e-04],
        [3.4570e-01],
        [5.7567e-02],
        [1.0000e+00],
        [9.9999e-01],
        [9.9996e-01],
        [2.7472e-03],
        [1.1940e-04],
        [6.2805e-01],
        [8.9327e-03],
        [1.0000e+00],
        [2.1224e-05],
        [9.9877e-01],
        [1.8826e-01],
        [5.8164e-02],
        [1.4068e-01],
        [1.0000e+00],
        [3.3889e-02],
        [8.3648e-02],
        [8.3976e-02],
        [1.0000e+00],
        [9.9988e-01],
        [9.9979e-01],
        [9.9075e-01],
        [1.0552e-06],
        [9.0164e-01],
        [7.0831e-04],
        [9.9982e-01],
        [6.3704e-01],
        [3.9579e-01],
        [4.4907e-01],
        [1.3004e-04],
        [1.4617e-02],
        [4.3597e-03],
        [5.2764e-04],
        [8.2069e-02],
        [3.6389e-05],
        [1.5809e-04],
        [9.6959e-01],
        [9.9984e-01],
        [8.4926e-03],
        [9.9919e-01],
        [1.8112e-02],
        [9.9928e-01],
        [4.0212e-04],
        [6.0188e-03],
        [1.1157e-04],
        [2.1351e-02],
        [3.5396e-04],
        [5.2107e-04],
        [7.4626e-03],
        [9.9934e-01],
        [3.9307e-02],
        [8.1029e-03],
        [6.7932e-02],
        [3.2533e-01],
        [1.0000e+00],
        [1.0000e+00],
        [7.9967e-01],
        [9.5046e-01],
        [7.7049e-01],
        [1.9011e-02],
        [3.5601e-04],
        [1.4809e-01],
        [9.9738e-01],
        [9.9999e-01],
        [8.3435e-05],
        [1.3426e-04],
        [7.7246e-05],
        [9.1969e-01],
        [6.6618e-03],
        [9.8303e-01],
        [4.3195e-03],
        [1.0282e-02],
        [9.9993e-01],
        [9.7902e-01],
        [4.0216e-02],
        [9.4052e-01],
        [2.9829e-06],
        [1.0000e+00],
        [9.5612e-01],
        [9.9833e-01],
        [1.6278e-03],
        [9.4635e-02],
        [1.0000e+00],
        [9.9945e-01],
        [3.6997e-01],
        [1.5906e-05],
        [1.1458e-05],
        [2.7246e-02],
        [6.8830e-05],
        [1.0000e+00],
        [3.9710e-03],
        [7.7357e-04],
        [9.9462e-05],
        [4.3834e-02],
        [8.5625e-02],
        [2.7077e-02],
        [5.0543e-02],
        [9.9973e-01],
        [6.7738e-01],
        [7.2725e-04],
        [9.3383e-04],
        [4.7527e-04],
        [1.5807e-04],
        [1.0000e+00],
        [1.0000e+00],
        [1.2692e-02],
        [3.5394e-05],
        [1.0000e+00],
        [1.7745e-03],
        [3.2146e-06],
        [9.9403e-01],
        [3.8781e-03],
        [9.9999e-01],
        [3.2229e-03],
        [9.9927e-01],
        [3.5737e-02],
        [1.2656e-02],
        [9.9988e-01],
        [6.4056e-01],
        [9.9585e-01],
        [1.0000e+00],
        [9.8350e-01],
        [1.2669e-05],
        [9.9999e-01],
        [2.5512e-02],
        [3.0424e-01],
        [7.7358e-03],
        [2.9809e-05],
        [3.6697e-04],
        [4.6754e-05],
        [4.1562e-02],
        [3.3139e-02],
        [9.9962e-01],
        [8.8507e-03],
        [2.9087e-02],
        [2.3640e-03],
        [9.4552e-02],
        [1.0000e+00],
        [2.1863e-02],
        [4.0843e-01],
        [1.0000e+00],
        [9.9962e-01],
        [1.3079e-01],
        [9.6509e-01],
        [9.9517e-01],
        [1.0294e-02],
        [7.7469e-04],
        [9.1899e-01],
        [3.4986e-05],
        [1.5947e-03],
        [4.6429e-06],
        [1.5166e-02],
        [7.8050e-04],
        [9.9998e-01],
        [6.6813e-01],
        [6.4702e-01],
        [9.5171e-02],
        [1.8254e-02],
        [3.0585e-01],
        [1.0000e+00],
        [1.6896e-04],
        [1.0740e-02],
        [9.6879e-01],
        [9.1722e-01],
        [9.5644e-01],
        [7.3525e-03],
        [1.0172e-02],
        [4.3520e-04],
        [4.2604e-04],
        [5.0507e-04],
        [1.0000e+00],
        [4.0372e-02],
        [5.5821e-01],
        [3.9618e-07],
        [9.9987e-01],
        [8.6739e-05],
        [2.6289e-05],
        [1.6881e-02],
        [1.5605e-02],
        [5.7307e-05],
        [9.9977e-01],
        [7.9224e-05],
        [1.7989e-05],
        [2.3030e-04],
        [9.0922e-01],
        [9.9990e-01],
        [9.3691e-01],
        [1.0626e-03],
        [4.6747e-05],
        [1.3219e-02],
        [1.5774e-04],
        [2.0153e-05],
        [1.7281e-03],
        [4.1647e-02],
        [1.9598e-01],
        [1.8971e-01],
        [9.9954e-01],
        [9.9470e-01],
        [3.5187e-02],
        [5.5233e-01],
        [1.0000e+00],
        [5.6436e-02],
        [2.1444e-05],
        [9.9999e-01],
        [9.9991e-01],
        [6.6265e-01],
        [1.2539e-04],
        [2.9561e-03],
        [5.7996e-04],
        [3.1901e-02],
        [1.8806e-02],
        [9.9834e-01],
        [2.3217e-03],
        [1.9416e-01],
        [1.7108e-01],
        [8.0026e-01],
        [9.8419e-01],
        [9.9998e-01],
        [2.8262e-01],
        [1.2862e-02],
        [2.2359e-04],
        [9.9990e-01],
        [1.7332e-03],
        [7.3190e-03],
        [9.9997e-01],
        [3.3042e-03],
        [1.3286e-03],
        [3.4286e-01],
        [1.3734e-03],
        [4.0081e-01],
        [7.3553e-01],
        [9.9999e-01],
        [9.9999e-01],
        [6.8871e-01],
        [9.9951e-01],
        [2.9186e-01],
        [1.0000e+00],
        [2.1525e-04],
        [9.8482e-01],
        [1.0000e+00],
        [9.9789e-01],
        [4.7576e-01],
        [9.8521e-04],
        [1.3552e-05],
        [9.9933e-01],
        [2.9805e-01],
        [1.0000e+00],
        [1.6264e-01],
        [9.9927e-01],
        [9.6689e-01],
        [2.7751e-04],
        [4.5088e-01],
        [4.0630e-02],
        [1.1065e-03],
        [6.2021e-04],
        [1.0147e-05],
        [9.9235e-01],
        [9.9997e-01],
        [7.1464e-03],
        [1.3133e-02],
        [5.3217e-01],
        [6.1554e-03],
        [4.4696e-04],
        [6.4751e-03],
        [9.6542e-01],
        [1.0000e+00],
        [8.1518e-03],
        [3.8503e-04],
        [1.2268e-04],
        [4.2777e-03],
        [8.1203e-01],
        [1.4447e-05],
        [1.1841e-02],
        [1.0000e+00],
        [9.9522e-01],
        [3.2043e-03],
        [7.5506e-02],
        [9.9827e-01],
        [4.2992e-05],
        [9.9999e-01],
        [9.9992e-01],
        [5.8975e-02],
        [9.9990e-01],
        [1.4052e-03],
        [3.6043e-02],
        [4.0313e-04],
        [1.0000e+00],
        [1.0000e+00],
        [7.2190e-04],
        [4.2083e-02],
        [2.1283e-01],
        [1.0000e+00],
        [2.3695e-03],
        [5.2057e-01],
        [9.6139e-01],
        [1.3852e-06],
        [2.9776e-04],
        [2.5019e-01],
        [9.3507e-06],
        [6.9271e-01],
        [1.0000e+00],
        [2.0416e-03],
        [9.9987e-01],
        [9.8126e-03],
        [1.1712e-04],
        [1.6153e-02],
        [6.8734e-03],
        [9.9916e-01],
        [9.5478e-01],
        [8.5508e-03],
        [5.9903e-05],
        [3.0106e-01],
        [2.9677e-01],
        [2.0563e-02],
        [1.7309e-03],
        [1.0049e-06],
        [2.3286e-02],
        [9.9999e-01],
        [9.9999e-01],
        [9.9456e-01],
        [9.9994e-01],
        [3.8347e-05],
        [1.0000e+00],
        [1.3468e-04],
        [9.9995e-01],
        [2.7792e-05],
        [1.2420e-02],
        [9.9999e-01],
        [3.3293e-02],
        [3.3736e-02],
        [2.3916e-02],
        [9.9991e-01],
        [9.9983e-01]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)
tensor([[5.0941e-01],
        [9.7292e-01],
        [8.0651e-02],
        [9.9999e-01],
        [1.0000e+00],
        [8.1970e-04],
        [3.8502e-01],
        [8.8785e-01],
        [4.9510e-01],
        [3.6432e-06],
        [3.3922e-06],
        [1.0000e+00],
        [3.7921e-01],
        [3.3530e-04],
        [9.9959e-01],
        [1.1886e-03],
        [9.8905e-01],
        [8.8500e-05],
        [9.9993e-01],
        [1.3977e-03],
        [1.6020e-01],
        [4.3304e-02],
        [2.2282e-01],
        [5.6818e-02],
        [5.1404e-03],
        [9.9845e-01],
        [1.6219e-01],
        [9.4683e-01],
        [1.4133e-02],
        [9.9922e-01],
        [9.9999e-01],
        [9.9572e-01],
        [9.9998e-01],
        [9.9830e-01],
        [8.7178e-01],
        [9.9590e-01],
        [4.0403e-02],
        [8.5369e-04],
        [9.8433e-01],
        [2.6345e-04],
        [1.0000e+00],
        [9.9998e-01],
        [7.6033e-01],
        [8.1483e-01],
        [9.9952e-01],
        [6.5717e-07],
        [2.1040e-02],
        [1.8501e-01],
        [9.9894e-01],
        [4.6295e-05],
        [9.8361e-01],
        [2.7733e-01],
        [3.4401e-03],
        [2.4289e-04],
        [2.9282e-02],
        [9.9962e-01],
        [7.5155e-01],
        [9.9580e-01],
        [2.9348e-01],
        [7.0850e-03],
        [7.4644e-01],
        [1.1903e-02],
        [4.9723e-03],
        [7.4353e-02],
        [9.9850e-01],
        [1.4589e-04],
        [5.3529e-01],
        [7.8295e-02],
        [9.9991e-01],
        [8.0669e-01],
        [1.0000e+00],
        [7.6067e-04],
        [9.9996e-01],
        [5.9253e-04],
        [9.9681e-01],
        [2.5843e-01],
        [5.5852e-03],
        [9.7844e-01],
        [7.3009e-01],
        [3.3929e-02],
        [1.0000e+00],
        [2.2506e-03],
        [5.3282e-06],
        [9.9319e-01],
        [9.9976e-01],
        [3.3504e-04],
        [9.8243e-01],
        [1.5871e-02],
        [3.9569e-02],
        [7.1727e-02],
        [1.0000e+00],
        [9.9999e-01],
        [1.0018e-06],
        [1.0000e+00],
        [1.0000e+00],
        [9.0512e-01],
        [9.9984e-01],
        [2.8304e-04],
        [2.3831e-02],
        [2.0036e-02],
        [9.9995e-01],
        [9.9937e-01],
        [6.7075e-04],
        [9.9097e-01],
        [1.8522e-02],
        [7.2944e-03],
        [1.1664e-05],
        [6.5706e-01],
        [1.0702e-03],
        [2.3147e-02],
        [7.3181e-02],
        [9.9370e-01],
        [1.7428e-01],
        [5.6151e-03],
        [1.5771e-01],
        [4.8090e-02],
        [1.3968e-01],
        [2.2102e-03],
        [4.2453e-01],
        [9.9998e-01],
        [5.9279e-04],
        [3.4570e-01],
        [5.7567e-02],
        [1.0000e+00],
        [9.9999e-01],
        [9.9996e-01],
        [2.7472e-03],
        [1.1940e-04],
        [6.2805e-01],
        [8.9327e-03],
        [1.0000e+00],
        [2.1224e-05],
        [9.9877e-01],
        [1.8826e-01],
        [5.8164e-02],
        [1.4068e-01],
        [1.0000e+00],
        [3.3889e-02],
        [8.3648e-02],
        [8.3976e-02],
        [1.0000e+00],
        [9.9988e-01],
        [9.9979e-01],
        [9.9075e-01],
        [1.0552e-06],
        [9.0164e-01],
        [7.0831e-04],
        [9.9982e-01],
        [6.3704e-01],
        [3.9579e-01],
        [4.4907e-01],
        [1.3004e-04],
        [1.4617e-02],
        [4.3597e-03],
        [5.2764e-04],
        [8.2069e-02],
        [3.6389e-05],
        [1.5809e-04],
        [9.6959e-01],
        [9.9984e-01],
        [8.4926e-03],
        [9.9919e-01],
        [1.8112e-02],
        [9.9928e-01],
        [4.0212e-04],
        [6.0188e-03],
        [1.1157e-04],
        [2.1351e-02],
        [3.5396e-04],
        [5.2107e-04],
        [7.4626e-03],
        [9.9934e-01],
        [3.9307e-02],
        [8.1029e-03],
        [6.7932e-02],
        [3.2533e-01],
        [1.0000e+00],
        [1.0000e+00],
        [7.9967e-01],
        [9.5046e-01],
        [7.7049e-01],
        [1.9011e-02],
        [3.5601e-04],
        [1.4809e-01],
        [9.9738e-01],
        [9.9999e-01],
        [8.3435e-05],
        [1.3426e-04],
        [7.7246e-05],
        [9.1969e-01],
        [6.6618e-03],
        [9.8303e-01],
        [4.3195e-03],
        [1.0282e-02],
        [9.9993e-01],
        [9.7902e-01],
        [4.0216e-02],
        [9.4052e-01],
        [2.9829e-06],
        [1.0000e+00],
        [9.5612e-01],
        [9.9833e-01],
        [1.6278e-03],
        [9.4635e-02],
        [1.0000e+00],
        [9.9945e-01],
        [3.6997e-01],
        [1.5906e-05],
        [1.1458e-05],
        [2.7246e-02],
        [6.8830e-05],
        [1.0000e+00],
        [3.9710e-03],
        [7.7357e-04],
        [9.9462e-05],
        [4.3834e-02],
        [8.5625e-02],
        [2.7077e-02],
        [5.0543e-02],
        [9.9973e-01],
        [6.7738e-01],
        [7.2725e-04],
        [9.3383e-04],
        [4.7527e-04],
        [1.5807e-04],
        [1.0000e+00],
        [1.0000e+00],
        [1.2692e-02],
        [3.5394e-05],
        [1.0000e+00],
        [1.7745e-03],
        [3.2146e-06],
        [9.9403e-01],
        [3.8781e-03],
        [9.9999e-01],
        [3.2229e-03],
        [9.9927e-01],
        [3.5737e-02],
        [1.2656e-02],
        [9.9988e-01],
        [6.4056e-01],
        [9.9585e-01],
        [1.0000e+00],
        [9.8350e-01],
        [1.2669e-05],
        [9.9999e-01],
        [2.5512e-02],
        [3.0424e-01],
        [7.7358e-03],
        [2.9809e-05],
        [3.6697e-04],
        [4.6754e-05],
        [4.1562e-02],
        [3.3139e-02],
        [9.9962e-01],
        [8.8507e-03],
        [2.9087e-02],
        [2.3640e-03],
        [9.4552e-02],
        [1.0000e+00],
        [2.1863e-02],
        [4.0843e-01],
        [1.0000e+00],
        [9.9962e-01],
        [1.3079e-01],
        [9.6509e-01],
        [9.9517e-01],
        [1.0294e-02],
        [7.7469e-04],
        [9.1899e-01],
        [3.4986e-05],
        [1.5947e-03],
        [4.6429e-06],
        [1.5166e-02],
        [7.8050e-04],
        [9.9998e-01],
        [6.6813e-01],
        [6.4702e-01],
        [9.5171e-02],
        [1.8254e-02],
        [3.0585e-01],
        [1.0000e+00],
        [1.6896e-04],
        [1.0740e-02],
        [9.6879e-01],
        [9.1722e-01],
        [9.5644e-01],
        [7.3525e-03],
        [1.0172e-02],
        [4.3520e-04],
        [4.2604e-04],
        [5.0507e-04],
        [1.0000e+00],
        [4.0372e-02],
        [5.5821e-01],
        [3.9618e-07],
        [9.9987e-01],
        [8.6739e-05],
        [2.6289e-05],
        [1.6881e-02],
        [1.5605e-02],
        [5.7307e-05],
        [9.9977e-01],
        [7.9224e-05],
        [1.7989e-05],
        [2.3030e-04],
        [9.0922e-01],
        [9.9990e-01],
        [9.3691e-01],
        [1.0626e-03],
        [4.6747e-05],
        [1.3219e-02],
        [1.5774e-04],
        [2.0153e-05],
        [1.7281e-03],
        [4.1647e-02],
        [1.9598e-01],
        [1.8971e-01],
        [9.9954e-01],
        [9.9470e-01],
        [3.5187e-02],
        [5.5233e-01],
        [1.0000e+00],
        [5.6436e-02],
        [2.1444e-05],
        [9.9999e-01],
        [9.9991e-01],
        [6.6265e-01],
        [1.2539e-04],
        [2.9561e-03],
        [5.7996e-04],
        [3.1901e-02],
        [1.8806e-02],
        [9.9834e-01],
        [2.3217e-03],
        [1.9416e-01],
        [1.7108e-01],
        [8.0026e-01],
        [9.8419e-01],
        [9.9998e-01],
        [2.8262e-01],
        [1.2862e-02],
        [2.2359e-04],
        [9.9990e-01],
        [1.7332e-03],
        [7.3190e-03],
        [9.9997e-01],
        [3.3042e-03],
        [1.3286e-03],
        [3.4286e-01],
        [1.3734e-03],
        [4.0081e-01],
        [7.3553e-01],
        [9.9999e-01],
        [9.9999e-01],
        [6.8871e-01],
        [9.9951e-01],
        [2.9186e-01],
        [1.0000e+00],
        [2.1525e-04],
        [9.8482e-01],
        [1.0000e+00],
        [9.9789e-01],
        [4.7576e-01],
        [9.8521e-04],
        [1.3552e-05],
        [9.9933e-01],
        [2.9805e-01],
        [1.0000e+00],
        [1.6264e-01],
        [9.9927e-01],
        [9.6689e-01],
        [2.7751e-04],
        [4.5088e-01],
        [4.0630e-02],
        [1.1065e-03],
        [6.2021e-04],
        [1.0147e-05],
        [9.9235e-01],
        [9.9997e-01],
        [7.1464e-03],
        [1.3133e-02],
        [5.3217e-01],
        [6.1554e-03],
        [4.4696e-04],
        [6.4751e-03],
        [9.6542e-01],
        [1.0000e+00],
        [8.1518e-03],
        [3.8503e-04],
        [1.2268e-04],
        [4.2777e-03],
        [8.1203e-01],
        [1.4447e-05],
        [1.1841e-02],
        [1.0000e+00],
        [9.9522e-01],
        [3.2043e-03],
        [7.5506e-02],
        [9.9827e-01],
        [4.2992e-05],
        [9.9999e-01],
        [9.9992e-01],
        [5.8975e-02],
        [9.9990e-01],
        [1.4052e-03],
        [3.6043e-02],
        [4.0313e-04],
        [1.0000e+00],
        [1.0000e+00],
        [7.2190e-04],
        [4.2083e-02],
        [2.1283e-01],
        [1.0000e+00],
        [2.3695e-03],
        [5.2057e-01],
        [9.6139e-01],
        [1.3852e-06],
        [2.9776e-04],
        [2.5019e-01],
        [9.3507e-06],
        [6.9271e-01],
        [1.0000e+00],
        [2.0416e-03],
        [9.9987e-01],
        [9.8126e-03],
        [1.1712e-04],
        [1.6153e-02],
        [6.8734e-03],
        [9.9916e-01],
        [9.5478e-01],
        [8.5508e-03],
        [5.9903e-05],
        [3.0106e-01],
        [2.9677e-01],
        [2.0563e-02],
        [1.7309e-03],
        [1.0049e-06],
        [2.3286e-02],
        [9.9999e-01],
        [9.9999e-01],
        [9.9456e-01],
        [9.9994e-01],
        [3.8347e-05],
        [1.0000e+00],
        [1.3468e-04],
        [9.9995e-01],
        [2.7792e-05],
        [1.2420e-02],
        [9.9999e-01],
        [3.3293e-02],

In [41]:
model.bias

tensor([-0.0019], dtype=torch.float64, requires_grad=True)

Evaluation

In [46]:
#model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()

print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5280086398124695